#!/bin/bash

# Supabase Schema Sync - Pull Script
# This script pulls the current schema from Supabase and generates migration files

set -e  # Exit on any error

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
MIGRATIONS_DIR="$PROJECT_ROOT/supabase/migrations"
LOG_FILE="$PROJECT_ROOT/sync.log"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging function
log() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1" | tee -a "$LOG_FILE"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" | tee -a "$LOG_FILE"
    exit 1
}

success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1" | tee -a "$LOG_FILE"
}

warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a "$LOG_FILE"
}

# Check if Supabase CLI is installed
check_supabase_cli() {
    if ! command -v supabase &> /dev/null; then
        error "Supabase CLI is not installed. Please install it first: npm install -g supabase"
    fi
    log "Supabase CLI found: $(supabase --version)"
}

# Check if we're in a git repository
check_git_repo() {
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        error "Not in a git repository. Please initialize git first."
    fi
    log "Git repository detected"
}

# Check if Supabase project is linked
check_supabase_project() {
    if [ ! -f "$PROJECT_ROOT/supabase/config.toml" ]; then
        error "Supabase project not initialized. Run 'supabase init' first."
    fi
    
    # Check if project is linked
    if ! supabase status > /dev/null 2>&1; then
        warning "Supabase project not linked. Attempting to link..."
        if [ -z "$SUPABASE_PROJECT_ID" ]; then
            error "SUPABASE_PROJECT_ID environment variable not set"
        fi
        supabase link --project-ref "$SUPABASE_PROJECT_ID"
    fi
    
    log "Supabase project linked successfully"
}

# Create migrations directory if it doesn't exist
ensure_migrations_dir() {
    if [ ! -d "$MIGRATIONS_DIR" ]; then
        mkdir -p "$MIGRATIONS_DIR"
        log "Created migrations directory: $MIGRATIONS_DIR"
    fi
}

# Pull current schema from Supabase
pull_schema() {
    log "Pulling current schema from Supabase..."
    
    # Create a temporary directory for the pull
    TEMP_DIR=$(mktemp -d)
    
    # Pull the schema
    if supabase db pull --schema public --file "$TEMP_DIR/schema.sql"; then
        success "Schema pulled successfully"
    else
        error "Failed to pull schema from Supabase"
    fi
    
    # Check if there are any differences
    if [ -f "$MIGRATIONS_DIR/latest_schema.sql" ]; then
        if diff -q "$TEMP_DIR/schema.sql" "$MIGRATIONS_DIR/latest_schema.sql" > /dev/null; then
            log "No schema changes detected"
            rm -rf "$TEMP_DIR"
            return 0
        else
            log "Schema changes detected"
        fi
    else
        log "No previous schema found, treating as new"
    fi
    
    # Generate migration file
    generate_migration "$TEMP_DIR/schema.sql"
    
    # Clean up
    rm -rf "$TEMP_DIR"
}

# Generate migration file
generate_migration() {
    local schema_file="$1"
    local timestamp=$(date +%Y%m%d%H%M%S)
    local migration_name="sync_${timestamp}"
    local migration_file="$MIGRATIONS_DIR/${timestamp}_${migration_name}.sql"
    
    log "Generating migration: $migration_file"
    
    # Copy the schema as the migration
    cp "$schema_file" "$migration_file"
    
    # Update the latest schema reference
    cp "$schema_file" "$MIGRATIONS_DIR/latest_schema.sql"
    
    # Add migration metadata
    cat >> "$migration_file" << EOF

-- Migration: $migration_name
-- Generated: $(date)
-- Source: Supabase schema pull
-- Description: Automated schema sync from Supabase

-- This migration was automatically generated by sync_pull.sh
-- Please review before applying to production
EOF

    success "Migration file created: $migration_file"
}

# Commit changes to git
commit_changes() {
    log "Committing schema changes to git..."
    
    # Add all migration files
    git add "$MIGRATIONS_DIR/"
    
    # Check if there are changes to commit
    if git diff --staged --quiet; then
        log "No changes to commit"
        return 0
    fi
    
    # Commit with descriptive message
    local commit_msg="feat: sync schema from Supabase $(date +%Y-%m-%d\ %H:%M:%S)"
    git commit -m "$commit_msg"
    
    success "Changes committed: $commit_msg"
}

# Main execution
main() {
    log "Starting Supabase schema pull..."
    
    # Pre-flight checks
    check_supabase_cli
    check_git_repo
    check_supabase_project
    ensure_migrations_dir
    
    # Pull schema and generate migrations
    pull_schema
    
    # Commit changes
    commit_changes
    
    success "Schema pull completed successfully!"
    
    # Show summary
    echo ""
    log "Summary:"
    echo "  - Migrations directory: $MIGRATIONS_DIR"
    echo "  - Log file: $LOG_FILE"
    echo "  - Latest schema: $MIGRATIONS_DIR/latest_schema.sql"
    echo ""
    log "Next steps:"
    echo "  1. Review the generated migration files"
    echo "  2. Run 'scripts/sync_push.sh --dry-run' to test"
    echo "  3. Run 'scripts/sync_push.sh' to apply changes"
}

# Handle command line arguments
case "${1:-}" in
    --help|-h)
        echo "Usage: $0 [options]"
        echo ""
        echo "Options:"
        echo "  --help, -h     Show this help message"
        echo "  --force        Force pull even if no changes detected"
        echo ""
        echo "Environment variables:"
        echo "  SUPABASE_PROJECT_ID    Supabase project ID"
        echo "  SUPABASE_SERVICE_ROLE_KEY  Service role key for authentication"
        echo ""
        exit 0
        ;;
    --force)
        log "Force mode enabled - will generate migration even if no changes detected"
        # This would modify the pull_schema function to always generate a migration
        ;;
esac

# Run main function
main "$@"
